# Generated by Django 3.1.7 on 2021-12-20 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='degree_programs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(default='uni2.png', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='diploma_programs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(default='uni1.png', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='hnd_programs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(default='uni1.png', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='school',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('desc', models.CharField(blank=True, max_length=1000, null=True)),
                ('school_type', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('website', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(default='uni1.png', upload_to='')),
                ('degree', models.ManyToManyField(blank=True, to='GES.degree_programs')),
                ('diploma', models.ManyToManyField(blank=True, to='GES.diploma_programs')),
                ('hnd', models.ManyToManyField(blank=True, to='GES.hnd_programs')),
            ],
        ),
    ]
