# Generated by Django 3.1.7 on 2021-12-25 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GES', '0006_auto_20211225_2121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='degree_programs',
            old_name='duratioin',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='diploma_programs',
            old_name='duratioin',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='hnd_programs',
            old_name='duratioin',
            new_name='duration',
        ),
    ]
